### PR TITLE
Update Etch.OrchardCore.Widgets And Fields reference to 0.5.1

### PR DESCRIPTION
**Pull request by JoeBerkley**

### CODE REVIEW

**Comment by peterkeating** [comment]
@JoeBerkley Code looks good but should we be worried about the build failing?

**Comment by peterkeating** [comment]
@JoeBerkley Probably worth upgrading `Etch.OrchardCore.Fields` too.

**Comment by JoeBerkley** [comment]
> @JoeBerkley Code looks good but should we be worried about the build failing?
Probably, I'll take another look when I get a chance 😄

**Comment by JoeBerkley** [comment]
I've now also updated the fields to `0.5.1-beta`, this is also why the build was failing as Widgets relied on 0.5.1 however the boilerplate was still relying on 0.4.0.

**Pull request merged**
